{{- if .Values.alertmanager.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-pvc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/name: alertmanager
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.alertmanager.storage.className }}
  resources:
    requests:
      storage: {{ .Values.alertmanager.storage.size }}
{{- end }}
