{{- if .Values.loki.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.loki.service.type }}
  ports:
    - name: http
      port: {{ .Values.loki.service.port }}
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 9095
      targetPort: grpc
      protocol: TCP
  selector:
    {{- include "monitoring.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/name: loki
{{- end }}
