{{- if .Values.loki.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: server
spec:
  replicas: {{ .Values.loki.replicaCount }}
  selector:
    matchLabels:
      {{- include "monitoring.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: loki
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        {{- include "monitoring.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/name: loki
        app.kubernetes.io/component: server
    spec:
      serviceAccountName: loki
      securityContext:
        {{- toYaml .Values.loki.podSecurityContext | nindent 8 }}
      containers:
        - name: loki
          image: "{{ .Values.loki.image.repository }}:{{ .Values.loki.image.tag }}"
          imagePullPolicy: {{ .Values.loki.image.pullPolicy }}
          args:
            - '-config.file=/etc/loki/loki-config.yml'
          ports:
            - name: http
              containerPort: 3100
              protocol: TCP
            - name: grpc
              containerPort: 9095
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: storage
              mountPath: /loki
          livenessProbe:
            httpGet:
              path: /ready
              port: http
            {{- toYaml .Values.loki.livenessProbe | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            {{- toYaml .Values.loki.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.loki.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: loki-config
        - name: storage
          persistentVolumeClaim:
            claimName: loki-pvc
      affinity:
        podAntiAffinity:
          {{- toYaml .Values.loki.affinity.podAntiAffinity | nindent 10 }}
{{- end }}
