{{- if .Values.prometheus.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/name: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.prometheus.storage.className }}
  resources:
    requests:
      storage: {{ .Values.prometheus.storage.size }}
{{- end }}
