apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api.yaml
  - data-service.yaml
  - orchestrator.yaml
  - backend.yaml
  - api/hpa-tuned.yaml
  - data-service/hpa-tuned.yaml
  - orchestrator/hpa-tuned.yaml
