apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- statefulset.yaml
- service.yaml
- configmap.yaml

images:
- name: neo4j
  newName: neo4j
  newTag: 5.15-community

commonLabels:
  app.kubernetes.io/name: neo4j
  app.kubernetes.io/component: database
  app.kubernetes.io/part-of: insurance-lead-gen
