apiVersion: v2
name: frontend
description: Insurance Lead Gen Frontend (Next.js) Helm Chart
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: common
    version: "1.0.0"
    repository: "file://../common"

maintainers:
  - name: Insurance AI Team
    email: team@insurance-lead-gen.local

keywords:
  - insurance
  - lead-generation
  - frontend
  - nextjs
