collector:
  zipkin:
    host-port: :9411
  otlp:
    enabled: true
    grpc:
      host-port: :4317
    http:
      host-port: :4318

sampling:
  default_strategy:
    type: probabilistic
    param: 0.1

storage:
  type: elasticsearch
  elasticsearch:
    server-urls: ["http://elasticsearch:9200"]
