apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  labels:
    app.kubernetes.io/name: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3  # AWS EBS GP3
  resources:
    requests:
      storage: 100Gi
