apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- statefulset.yaml
- service.yaml
- configmap.yaml
- backup-cronjob.yaml

images:
- name: postgres
  newName: postgres
  newTag: 16-alpine

commonLabels:
  app.kubernetes.io/name: postgres
  app.kubernetes.io/component: database
  app.kubernetes.io/part-of: insurance-lead-gen
