apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- rbac.yaml
- network-policies.yaml
- storage-classes.yaml
- ingress-controller.yaml

commonLabels:
  app.kubernetes.io/part-of: insurance-lead-gen
  app.kubernetes.io/component: infrastructure
