apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: insurance-lead-gen-dev

resources:
- namespace.yaml

bases:
- ../../base

patchesStrategicMerge:
- replicas-patch.yaml
- secrets-patch.yaml

images:
- name: insurance-lead-gen/api
  newName: insurance-lead-gen/api
  newTag: dev
- name: insurance-lead-gen/data-service
  newName: insurance-lead-gen/data-service
  newTag: dev
- name: insurance-lead-gen/orchestrator
  newName: insurance-lead-gen/orchestrator
  newTag: dev
- name: insurance-lead-gen/frontend
  newName: insurance-lead-gen/frontend
  newTag: dev
- name: insurance-lead-gen/backend
  newName: insurance-lead-gen/backend
  newTag: dev

commonLabels:
  environment: dev
