apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-pvc
  labels:
    app.kubernetes.io/name: loki
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3  # AWS EBS GP3
  resources:
    requests:
      storage: 50Gi
